install.packages(c("devtools","RcppArmadillo", "data.table", "Matrix"), dependencies=TRUE)
library(devtools)
install_github("tshmak/lassosum")
install.packages("ukbtools")
install.packages("mltools")
install.packages("scales")
install.packages("mgcv")
install.packages("BiocManager")
BiocManager::install("impute")
install.packages("bnstruct")
